sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.1
deploy:
  provider: script
  script:
    - which ruby
    - ruby -v
    - bundle exec rake deploy
  skip_cleanup: true
  on:
    branch: master